version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
    networks:
      - net

  frontend:
    image: hungngodev/flavorie-frontend:v1.0.${IMAGE_TAG}
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - net

  backend:
    image: hungngodev/flavorie-backend:v1.0.${IMAGE_TAG}
    restart: always
    networks:
      - net
    env_file: ./.env

  peerjs:
    image: hungngodev/flavorie-peerjs:v1.0.${IMAGE_TAG}
    ports:
      - "9001:9001"
    networks:
      - net

networks:
  net:
    external: true
