name: EC2 CD Pipeline on AWS

on:
  workflow_run:
    workflows: ["Docker CI for Docker Hub Pipeline"]
    types:
      - completed

jobs:
  ec2-cd:
    runs-on: self-hosted
    steps:
      - name: Export env and docker compose
        run: |
          cd Flavorie

        working-directory: /home/ubuntu
